### ISSUE TITLE
The onCapture callBack is causing this error in release and profile mode randomly: java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by igbokwenu** [Conezi/face_camera#31]
Full error message:
 /AndroidRuntime( 8848): Shutting down VM
E/AndroidRuntime( 8848): FATAL EXCEPTION: main
E/AndroidRuntime( 8848): Process: com.skylinefuturistic.handy_man, PID: 8848
E/AndroidRuntime( 8848): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 8848): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime( 8848): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:277)
E/AndroidRuntime( 8848): 	at io.flutter.plugins.camera.DartMessenger.lambda$error$2(DartMessenger.java:198)
E/AndroidRuntime( 8848): 	at io.flutter.plugins.camera.DartMessenger$$ExternalSyntheticLambda1.run(Unknown Source:8)
E/AndroidRuntime( 8848): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 8848): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 8848): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime( 8848): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime( 8848): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8848): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime( 8848): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/Process ( 8848): Sending signal. PID: 8848 SIG: 9

**Comment by Conezi** [comment]
Please upgrade to the latest version 0.1.1 to resolve this issue. If the error persists after upgrading, feel free to reopen the issue. Thank you!
