### ISSUE TITLE
this is the error i am getting

### ISSUE THREAD

**Issue by fisforfaheem** [Conezi/face_camera#37]
code i `used:`
```
import 'dart:io';

import 'package:beboro/widgets/bottom_bar/lender_custom_bottom_bar.dart';
import 'package:face_camera/face_camera.dart';
import 'package:flutter/material.dart';

import '../../../../core/app_export.dart';
import 'controller/selfie_verification_controller.dart';

class SelfieVerificationScreen extends GetWidget<SelfieVerificationController> {
  final String documentType;
  final XFile frontImage;
  final XFile backImage;

  SelfieVerificationScreen(
      {super.key,
      required this.documentType,
      required this.frontImage,
      required this.backImage});
  final selfieImage = Rx<XFile?>(null);
  // XFile? selfieImage;

  Widget _message(String msg) => Padding(
        padding: const EdgeInsets.symmetric(horizontal: 55, vertical: 15),
        child: Text(msg,
            textAlign: TextAlign.center,
            style: const TextStyle(
                fontSize: 14, height: 1.5, fontWeight: FontWeight.w400)),
      );
  @override
  Widget build(BuildContext context) {
    return SafeArea(
        child: Scaffold(
            appBar: _buildAppBar(),
            body: SizedBox(
              width: SizeUtils.width,
              child: SingleChildScrollView(
                child: Column(
                  children: [
                    SizedBox(height: 60.v),
                    Text("lbl_take_selfie".tr,
                        style: theme.textTheme.titleLarge),
                    SizedBox(height: 6.v),
                    Text("msg_follow_the_head".tr,
                        style: theme.textTheme.labelLarge),
                    SizedBox(height: 27.v),
                    // Container(
                    //     height: 232.v,
                    //     width: 254.h,
                    //     decoration: BoxDecoration(
                    //         color: appTheme.deepPurple10001,
                    //         borderRadius: BorderRadius.circular(5.h))),
                    SmartFaceCamera(
                      autoCapture: true,
                      defaultCameraLens: CameraLens.front,
                      onCapture: (File? image) {
                        if (image != null) {
                          selfieImage.value = XFile(image.path);
                        }
                      },
                      onFaceDetected: (Face? face) {
                        // Do something when a face is detected
                      },
                      messageBuilder: (context, face) {
                        if (face == null) {
                          return _message('Place your face in the camera');
                        }
                        if (!face.wellPositioned) {
                          return _message('Center your face in the square');
                        }
                        return const SizedBox.shrink();
                      },
                    ),
                    SizedBox(height: 27.v),
                    Text("msg_tilt_head_to_the".tr,
                        style: CustomTextStyles.labelLargeBlack900),
                    SizedBox(height: 113.v),
                    // _buildHeaderRow(),
                  ],
                ),
              ),
            ),
            bottomNavigationBar: _buildLenderBottomBar()));
  }

  Widget _buildLenderBottomBar() {
    return buildLenderBottomBar((BottomBarEnum type) {
      Get.toNamed(getCurrentRoute(type));
    });
  }

  /// Section Widget
  PreferredSizeWidget _buildAppBar() {
    return CustomAppBar(
        leadingWidth: 43.h,
        leading: AppbarLeadingIconbutton(
            imagePath: ImageConstant.imgGroup17,
            margin: EdgeInsets.only(left: 16.h, top: 10.v, bottom: 10.v),
            onTap: () {
              onTapIconButton();
            }),
        centerTitle: true,
        title: AppbarTitle(text: "lbl_id_verification".tr),
        actions: [
          Container(
              height: 20.adaptSize,
              width: 20.adaptSize,
              margin: EdgeInsets.symmetric(horizontal: 18.h, vertical: 10.v),
              decoration: BoxDecoration(
                  color: theme.colorScheme.onPrimary,
                  borderRadius: BorderRadius.circular(13.h)))
        ],
        styleType: Style.bgShadow);
  }

  /// Navigates to the uploadDocsScreen when the action is triggered.
  onTapIconButton() {
    // Get.toNamed(
    //   AppRoutes.uploadDocsScreen,
    // );
  }
}

```

I/Camera  (31148): refreshPreviewCaptureSession
2
I/Camera  (31148): CameraCaptureSession onClosed
W/System  (31148): A resource failed to call Surface.release. 
D/TransportRuntime.CctTransportBackend(31148): Making request to: https://firebaselogging.googleapis.com/v0cc/log/batch?format=json_proto3
D/TrafficStats(31148): tagSocket(124) with statsTag=0xffffffff, statsUid=-1
I/TransportRuntime.CctTransportBackend(31148): Status Code: 200
I/TransportRuntime.CctTransportBackend(31148): Content-Type: application/json; charset=UTF-8
I/TransportRuntime.CctTransportBackend(31148): Content-Encoding: gzip
I/.example.beboro(31148): Background concurrent copying GC freed 1885(135KB) AllocSpace objects, 49(30MB) LOS objects, 78% free, 6651KB/30MB, paused 44us,1.090ms total 100.301ms
I/.example.beboro(31148): Background young concurrent copying GC freed 1504(116KB) AllocSpace objects, 47(29MB) LOS objects, 36% free, 19MB/30MB, paused 1.574ms,25us total 241.184ms
E/flutter (31148): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (31148): #0      AndroidCamera._startStreamListener.<anonymous closure> (package:camera_android/src/android_camera.dart:353:29)
E/flutter (31148): #1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (31148): #2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (31148): #3      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (31148): #4      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (31148): #5      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (31148): #6      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (31148): #7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (31148):

**Comment by Conezi** [comment]
Please upgrade to the latest version 0.1.1 to resolve this issue. If the error persists after upgrading, feel free to reopen the issue. Thank you!
