### ISSUE TITLE
Error when close the page but not crash

### ISSUE THREAD

**Issue by andikatp** [Conezi/face_camera#58]
When i close the page that utilize the FaceCamera, my firebase crashlytics always showing logs like this
`I/flutter ( 3898): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 3898): A FaceCameraController was used after being disposed.
I/flutter ( 3898): Once you have called dispose() on a FaceCameraController, it can no longer be used.
I/flutter ( 3898): #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
I/flutter ( 3898): #1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
I/flutter ( 3898): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:412:27)
I/flutter ( 3898): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:555:5)
I/flutter ( 3898): #4      FaceCameraController._processImage (package:face_camera/src/controllers/face_camera_controller.dart:199:9)
I/flutter ( 3898): <asynchronous suspension>
I/flutter ( 3898): ----------------------------------------------------`

my code is normal
```  @override
  void onInit() {
    super.onInit();
    _initialize();
  }

  @override
  Future<void> onClose() async {
    try {
      await faceDetector.close();
      await faceController.stopImageStream();
      await faceController.dispose();
    } catch (e, s) {
      print(e);
      print(s);
    }
    super.onClose();
    super.dispose();
  }
  
   Future<void> _initialize() async {
    faceController = FaceCameraController(
      defaultCameraLens:
          FaceCamera.cameras.length > 1 ? CameraLens.front : CameraLens.back,
      enableAudio: false,
      performanceMode: FaceDetectorMode.accurate,
      onCapture: _takeImage,
      defaultFlashMode: CameraFlashMode.off,
      onFaceDetected: (_) {},
    );
    final options = FaceDetectorOptions(
      performanceMode: FaceDetectorMode.accurate,
      minFaceSize: 0.20,
    );
    faceDetector = FaceDetector(options: options);
    await faceController.initialize();
  }
  ```

**Comment by andikatp** [comment]
nvm i just remove `faceController.dispose` and it works
```
  @override
  Future<void> onClose() async {
    await faceDetector.close();
    super.onClose();
    super.dispose();
  }
```
